### ISSUE TITLE
保存分享图

### ISSUE THREAD

**Issue by Markl121** [JaimeCheng/canvasShareImg#4]
你好 生成图片后 我按保存分享图没有反应

是不是 canvas.js 里面
    //生产环境时 记得这里要加入获取相册授权的代码
    wx.saveImageToPhotosAlbum({
      filePath: that.data.prurl,

这里应该如何操作呢

**Comment by JaimeCheng** [comment]
不加授权代码也不影响保存分享图 ，在检查下是不是别的地方出错了
